### ISSUE TITLE
Error in http://www.cfg4j.org/ Quick Start. (Cfg4jPoweredApplication)

### ISSUE THREAD

**Issue by seaward** [cfg4j/cfg4j#132]
INFO( org.cfg4j.provider.ConfigurationProviderBuilder.build(ConfigurationProviderBuilder.java:135)  ) - Initializing ConfigurationProvider with org.cfg4j.source.git.GitConfigurationSource source, org.cfg4j.source.reload.strategy.PeriodicalReloadStrategy reload strategy and org.cfg4j.source.context.environment.DefaultEnvironment environment
 INFO( org.cfg4j.source.git.GitConfigurationSource.init(GitConfigurationSource.java:128)  ) - Initializing class org.cfg4j.source.git.GitConfigurationSource pointing to https://github.com/cfg4j/cfg4j-git-sample-config.git
Exception in thread "main" java.lang.IllegalStateException: Can't bind method friends
	at org.cfg4j.validator.BindingValidator.validate(BindingValidator.java:65)
	at org.cfg4j.provider.SimpleConfigurationProvider.bind(SimpleConfigurationProvider.java:128)
	at org.cfg4j.provider.SimpleConfigurationProvider.bind(SimpleConfigurationProvider.java:106)
	at com.synnex.conf.Cfg4jPoweredApplication.main(Cfg4jPoweredApplication.java:33)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.cfg4j.validator.BindingValidator.validate(BindingValidator.java:51)
	... 3 more
Caused by: org.cfg4j.source.context.environment.MissingEnvironmentException: Missing environment: 
	at org.cfg4j.source.git.GitConfigurationSource.getConfiguration(GitConfigurationSource.java:99)
	at org.cfg4j.provider.SimpleConfigurationProvider.getProperty(SimpleConfigurationProvider.java:91)
	at org.cfg4j.provider.SimpleConfigurationProvider.getProperty(SimpleConfigurationProvider.java:76)
	at org.cfg4j.provider.BindInvocationHandler.invoke(BindInvocationHandler.java:61)
	at com.sun.proxy.$Proxy0.friends(Unknown Source)
	... 8 more
Caused by: org.eclipse.jgit.api.errors.RefNotFoundException: Ref origin/master can not be resolved
	at org.eclipse.jgit.api.CreateBranchCommand.getStartPointObjectId(CreateBranchCommand.java:282)
	at org.eclipse.jgit.api.CreateBranchCommand.call(CreateBranchCommand.java:135)
	at org.eclipse.jgit.api.CheckoutCommand.call(CheckoutCommand.java:220)
	at org.cfg4j.source.git.GitConfigurationSource.checkoutToBranch(GitConfigurationSource.java:179)
	at org.cfg4j.source.git.GitConfigurationSource.getConfiguration(GitConfigurationSource.java:97)
	... 12 more

**Comment by norbertpotocki** [comment]
I fixed the branch name in the configuration repository. Re-run your code and it should work this time.

**Comment by seaward** [comment]
v 4.1.4 works now. But v 4.2.0 has below error:
 INFO( org.cfg4j.provider.ConfigurationProviderBuilder.build(ConfigurationProviderBuilder.java:132)  ) - Initializing ConfigurationProvider with org.cfg4j.source.git.GitConfigurationSource source, org.cfg4j.source.reload.strategy.PeriodicalReloadStrategy reload strategy and org.cfg4j.source.context.environment.DefaultEnvironment environment
 INFO( org.cfg4j.source.git.GitConfigurationSource.init(GitConfigurationSource.java:128)  ) - Initializing class org.cfg4j.source.git.GitConfigurationSource pointing to https://github.com/cfg4j/cfg4j-git-sample-config.git
Exception in thread "main" org.cfg4j.source.SourceCommunicationException: Unable to communicate with configuration source: Unable to clone repository: https://github.com/cfg4j/cfg4j-git-sample-config.git
	at org.cfg4j.source.git.GitConfigurationSource.init(GitConfigurationSource.java:144)
	at org.cfg4j.provider.ConfigurationProviderBuilder.build(ConfigurationProviderBuilder.java:142)
	at com.synnex.conf.Cfg4jPoweredApplication.main(Cfg4jPoweredApplication.java:30)
Caused by: org.eclipse.jgit.api.errors.TransportException: https://github.com/cfg4j/cfg4j-git-sample-config.git: cannot open git-upload-pack
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:134)
	at org.eclipse.jgit.api.CloneCommand.fetch(CloneCommand.java:201)
	at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:135)
	at org.cfg4j.source.git.GitConfigurationSource.init(GitConfigurationSource.java:139)
	... 2 more
Caused by: org.eclipse.jgit.errors.TransportException: https://github.com/cfg4j/cfg4j-git-sample-config.git: cannot open git-upload-pack
	at org.eclipse.jgit.transport.TransportHttp.connect(TransportHttp.java:518)
	at org.eclipse.jgit.transport.TransportHttp.openFetch(TransportHttp.java:296)
	at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:136)
	at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:122)
	at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1179)
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:128)
	... 5 more

**Comment by norbertpotocki** [comment]
Could you post your code for me to run and debug? I looks like you're experiencing a communication problem with GitHub.

**Comment by norbertpotocki** [comment]
Also, are you using a proxy by any chance?

**Comment by norbertpotocki** [comment]
Also - what is the exact version of Java that you're using to run the code?

**Comment by seaward** [comment]
I found out it's my computer's network issue, fixed now. Thanks a lot!
