### ISSUE TITLE
cfg4j-consul: Caused by: java.net.MalformedURLException: unknown protocol: null

### ISSUE THREAD

**Issue by zdlgrj** [cfg4j/cfg4j#163]
Hi, I am playing cfg4j for our configuration management framework using consul, after we installed the cf4j-consul dep(was trying to isolate the issue, so didn't apply other changes), most of our service POST endpoints failed with below exception: 

```
Caused by: java.net.MalformedURLException: unknown protocol: null
	at org.apache.cxf.transport.http.asyncclient.AsyncHTTPConduit.setupConnection(AsyncHTTPConduit.java:151)
	at org.apache.cxf.transport.http.HTTPConduit.prepare(HTTPConduit.java:497)
	at org.apache.cxf.interceptor.MessageSenderInterceptor.handleMessage(MessageSenderInterceptor.java:46)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.jaxrs.client.AbstractClient.doRunInterceptorChain(AbstractClient.java:652)
	at org.apache.cxf.jaxrs.client.WebClient.doChainedInvocation(WebClient.java:1097)
	... 33 more

```

fwiw, the media type we are posting is JSON type.

Looked closer, for our client impl, it was using org.glassfish.jersey.client.JerseyClient, but replaced with `org.apache.cxf.jaxrs.client.spec.ClientImpl`.

Then I found below in the source code, this is actually being used in cfg4j-consul?  or any other ideas?
```
compile group: "org.apache.cxf", name: "cxf-rt-rs-client", version: "3.1.6"
compile group: "org.apache.cxf", name: "cxf-rt-transports-http-hc", version: "3.1.6"
```

Thanks

**Comment by norbertpotocki** [comment]
Hi @zdlgrj,

So your other code stopped working when you included cfg4j dependency? Or did cfg4j stop to work? It would help greatly if you included the full stacktrace and a snippet showing how you called cfg4j.

**Comment by zdlgrj** [comment]
Yeah, more specifically, it failed when I included `cf4j-consul` dependency. I was trying to isolate the issue, it throws above exception when I only included cf4j-consul` dependency(no other changes).

I looked into some details: I was originally using 'JerseyClient' for my client impl, but it is override with Apache cxf client after I installed the dep. 

So I did this to exclude `org.apache.cxf` dependencies: 

```
  compile group: "org.cfg4j", name:"cfg4j-core", version: "4.4.0"
  compile([group: "org.cfg4j", name:"cfg4j-consul", version: "4.4.0"]) {
      exclude group: 'org.apache.cxf', module: 'cxf-rt-rs-client'
      exclude group: 'org.apache.cxf', module: 'cxf-rt-transports-http-hc'
  } 
```

Everything worked fine afterwards, I looked into the source code of cfg4j-consul, it seems org.apache.cxf is not being used anywhere. Should the dependencies be removed? I can submit a PR if you think that is good.
