### ISSUE TITLE
cfg4j-git doesn't support authentication with private git repositiries

### ISSUE THREAD

**Issue by rtybase** [cfg4j/cfg4j#180]
Try using cfg4j-git to access a private repository, using this demo as an example
https://github.com/cfg4j/cfg4j-sample-apps/tree/master/git-simple

First of all, there is no means to provide credentials to the private repo. Although, the underlying org.eclipse.jgit seems to parse the username and password from the repositoryURI, e.g. in CloneCommand class, line 133
`URIish u = new URIish(uri);`

And URIish class constructor, line 220

		matcher = FULL_URI.matcher(s);
		if (matcher.matches()) {
			scheme = matcher.group(1);
			user = unescape(matcher.group(2));
			pass = unescape(matcher.group(3));
			host = unescape(matcher.group(4));
			if (matcher.group(5) != null)
				port = Integer.parseInt(matcher.group(5));
			rawPath = cleanLeadingSlashes(
					n2e(matcher.group(6)) + n2e(matcher.group(7)), scheme);
			path = unescape(rawPath);
			return;
		}

And these details don't seem to be used at all. 

Further to this problem GitConfigurationSource class, e.g. line 147

    try {
      clonedRepo = Git.cloneRepository()
          .setURI(repositoryURI)
          .setDirectory(clonedRepoPath.toFile())
          .call();
    } catch (GitAPIException e) {
      throw new SourceCommunicationException("Unable to clone repository: " + repositoryURI, e);
    }

this doesn't inject a CredentialsProvider, like 

    try {
      clonedRepo = Git.cloneRepository()
          .setURI(repositoryURI)
          .setDirectory(clonedRepoPath.toFile())
          .setCredentialsProvider(credentialsProvider)
          .call();
    } catch (GitAPIException e) {
      throw new SourceCommunicationException("Unable to clone repository: " + repositoryURI, e);
    }

which is the right solution to sort out this problem.

**Comment by rtybase** [comment]
The exceptions thrown looks like:

    Exception in thread "main" org.cfg4j.source.SourceCommunicationException: Unable to communicate with configuration source: Unable to clone repository: https://bitbucket.org/....git
	at com.wandera.service.pocconfig.git.GitConfigurationSource.init(GitConfigurationSource.java:170)
	at org.cfg4j.provider.ConfigurationProviderBuilder.build(ConfigurationProviderBuilder.java:142)
	at com.wandera.service.pocconfig.util.FeatureFlagSourceType.buildProviderFrom(FeatureFlagSourceType.java:90)
	at com.wandera.service.pocconfig.util.FeatureFlagSourceType$3.buildProviderFrom(FeatureFlagSourceType.java:59)
	at com.wandera.service.pocconfig.PocConfigService.initialize(PocConfigService.java:36)
	at com.wandera.service.pocconfig.PocConfigService.initialize(PocConfigService.java:12)
	at com.yammer.dropwizard.AbstractService.initializeWithBundles(AbstractService.java:181)
	at com.yammer.dropwizard.cli.ServerCommand.run(ServerCommand.java:49)
	at com.yammer.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:98)
	at com.yammer.dropwizard.cli.Command.run(Command.java:111)
	at com.yammer.dropwizard.AbstractService.run(AbstractService.java:197)
	at com.wandera.service.pocconfig.PocConfigService.main(PocConfigService.java:26)
    Caused by: org.eclipse.jgit.api.errors.TransportException: https://bitbucket.org/....git: Authentication is required but no CredentialsProvider has been registered
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:135)
	at org.eclipse.jgit.api.CloneCommand.fetch(CloneCommand.java:202)
	at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:135)
	at com.wandera.service.pocconfig.git.GitConfigurationSource.init(GitConfigurationSource.java:168)
	... 11 more
    Caused by: org.eclipse.jgit.errors.TransportException: https://bitbucket.org/....git: Authentication is required but no CredentialsProvider has been registered
	at org.eclipse.jgit.transport.TransportHttp.connect(TransportHttp.java:485)
	at org.eclipse.jgit.transport.TransportHttp.openFetch(TransportHttp.java:288)
	at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:136)
	at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:122)
	at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1179)
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:128)
	... 14 more

**Comment by kirk-daries** [comment]
Just ran into this issue as well.

**Comment by Nare** [comment]
Hi I would like to use cfg4j for our production servers, But this issue stops me from doing it.
1. no way to pass git credentials. I don't want to open public access to my git repo. Of course I can set a firewall but that's not wanted.

Is this going to be fixed?

**Comment by aashishmodak** [comment]
Cant use this - as it does not support private git repos with credentials
