### ISSUE TITLE
java.lang.InternalError when retrieving the git files using cfg4j in production environment

### ISSUE THREAD

**Issue by bpkumar74** [cfg4j/cfg4j#194]
We are using cfg4j library to read property files from GIT in our application. This works great in Dev and Test. But when we pushed the code to Production like environment, (QA it is same as Production in setup and firewall, etc), we are getting InternalError. We tried following:
1. setting policy as  -Djava.security.policy=emx-java-policy.txt
2. setting proper cert file information like -Djavax.net.ssl.trustStore=, -Djavax.net.ssl.trustStorePassword=

nothing is working in this environment. Same code works in Test. Did anyone faced this and if so, how did you resolve this? Thanks

Exception in thread "main" java.lang.InternalError
        at sun.security.ec.SunEC.initialize(Native Method)
        at sun.security.ec.SunEC.access$000(SunEC.java:49)
        at sun.security.ec.SunEC$1.run(SunEC.java:61)
        at sun.security.ec.SunEC$1.run(SunEC.java:58)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.security.ec.SunEC.<clinit>(SunEC.java:58)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at java.lang.Class.newInstance(Class.java:383)
        at sun.security.jca.ProviderConfig$2.run(ProviderConfig.java:221)
        at sun.security.jca.ProviderConfig$2.run(ProviderConfig.java:206)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.security.jca.ProviderConfig.doLoadProvider(ProviderConfig.java:206)
        at sun.security.jca.ProviderConfig.getProvider(ProviderConfig.java:187)
        at sun.security.jca.ProviderList.getProvider(ProviderList.java:233)
        at sun.security.jca.ProviderList.getService(ProviderList.java:331)
        at sun.security.jca.GetInstance.getInstance(GetInstance.java:157)
        at javax.net.ssl.SSLContext.getInstance(SSLContext.java:156)
        at javax.net.ssl.SSLContext.getDefault(SSLContext.java:97)
        at javax.net.ssl.SSLSocketFactory.getDefault(SSLSocketFactory.java:121)
        at javax.net.ssl.HttpsURLConnection.getDefaultSSLSocketFactory(HttpsURLConnection.java:333)
        at javax.net.ssl.HttpsURLConnection.<init>(HttpsURLConnection.java:291)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.<init>(HttpsURLConnectionImpl.java:85)
        at sun.net.www.protocol.https.Handler.openConnection(Handler.java:62)
        at java.net.URL.openConnection(URL.java:1031)
        at org.eclipse.jgit.transport.http.JDKHttpConnection.<init>(JDKHttpConnection.java:93)
        at org.eclipse.jgit.transport.http.JDKHttpConnectionFactory.create(JDKHttpConnectionFactory.java:61)
        at org.eclipse.jgit.transport.TransportHttp.httpOpen(TransportHttp.java:530)
        at org.eclipse.jgit.transport.TransportHttp.httpOpen(TransportHttp.java:515)
        at org.eclipse.jgit.transport.TransportHttp.connect(TransportHttp.java:454)
        at org.eclipse.jgit.transport.TransportHttp.openFetch(TransportHttp.java:288)
        at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:136)
        at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:122)
        at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1179)
        at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:128)
        at org.eclipse.jgit.api.CloneCommand.fetch(CloneCommand.java:201)
        at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:135)
        at org.cfg4j.source.git.GitConfigurationSource.init(GitConfigurationSource.java:146)
        at org.cfg4j.provider.ConfigurationProviderBuilder.build(ConfigurationProviderBuilder.java:142

**Comment by bpkumar74** [comment]
This was caused by wrong Java path and also port issue for that host/port. Once those are corrected, it resolved the issue. Thanks
